name: 'BicepDelete'

on: 
  workflow_dispatch:

jobs:

  BicepDeploy:
    name: 'BicepDelete'
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: rg-bicep-samples
      ResourceGroupLocation: "japaneast"
    environment: production

    steps:

    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Bicep Build
      run: |
        az bicep build --file ./main.bicep

    - name: Delete Deployment Group
      uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az deployment group --name ${{ env.ResourceGroupName }} -g ${{ env.ResourceGroupName }}